version: '3'

services:
  nginx:
    build:
      dockerfile: containers/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./containers/nginx:/etc/nginx/http.d/
      - ./containers/nginx/certs:/etc/nginx/ssl/
      - wp-volume:/var/www/
    restart: always

  mariadb:
    build:
      dockerfile: containers/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PSW: ${DB_PSW}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

  wordpress:
    build:
      dockerfile: containers/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PSW: ${DB_PSW}
    container_name: wordpress
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    restart: always

  redis:
    build:
      dockerfile: containers/redis/Dockerfile
    container_name: redis
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  ftp:
    build:
      dockerfile: containers/ftp/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PSW: ${FTP_PSW}
    container_name: ftp
    depends_on:
      - wordpress
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  adminer:
    build:
      dockerfile: containers/adminer/Dockerfile
    container_name: adminer
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  app:
    build:
      dockerfile: containers/app/Dockerfile
    container_name: app
    ports:
      - "80:80"
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
