services:
  nginx:
    build:
      context: ./containers/nginx
      dockerfile: Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./containers/nginx:/etc/nginx/http.d/
      - ./containers/nginx/certs:/etc/nginx/ssl/
      - wp-volume:/var/www/html
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./containers/mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PSW}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT}
    ports:
      - "3306:3306"
    networks:
      - inception
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build:
      context: ./containers/wordpress
      dockerfile: Dockerfile
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PSW}
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    restart: always

  redis:
    container_name: redis
    build:
      context: ./containers/redis
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always

  ftp:
    container_name: ftp
    build:
      dockerfile: containers/ftp/Dockerfile
      args:
        FTP_USR: ${FTP_USR}
        FTP_PSW: ${FTP_PSW}
    depends_on:
      - wordpress
    ports:
      - "21:21"
    volumes:
      - wp-volume:/var/www/
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    build:
      dockerfile: containers/adminer/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always

  app:
    container_name: app
    build:
      dockerfile: containers/app/Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
